datasource:
  params:
    path: transaction_data.csv
  type: csv
embedding:
  params:
    api_key: "GET FROM ENV VARIABLE"
    model: text-embedding-ada-002
  type: openai
llm:
  params:
    api_key: "GET FROM ENV VARIABLE"
    model: gpt-4o-mini
  type: openai
vectordb:
  params:
    persist_directory: ./chromadb
  type: chromadb
