datasource:
  params:
    path: transaction_data.csv
  type: csv
embedding:
  params:
    #api_key: "PULL FROM ENVIRONMENT VARIABLE"
    model: text-embedding-ada-002
  type: openai
llm:
  params:
    #api_key: "PULL FROM ENVIRONMENT VARIABLE"
    model: gpt-4o-mini
  type: openai
vectordb:
  params:
    persist_directory: ./chromadb
  type: chromadb
